// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UML;

/************************************************************/
/**
 * 
 */
public class Alumne {
	/**
	 * 
	 */
	private int idAlumne;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String matricula;
};
