// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UML;

/************************************************************/
/**
 * 
 */
public class Professor {
	/**
	 * 
	 */
	private static int idProfessor;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	public int edat;
	/**
	 * 
	 */
	private String pnom;
	/**
	 * 
	 */
};
